### ISSUE TITLE
output doesn't match ros2 topic echo

### ISSUE THREAD

**Issue by stewpend0us** [PlotJuggler/plotjuggler-ros-plugins#73] opened 2023-11-27 20:10 UTC
When I use regular old "ros2 topic echo" I get different output then I get when using plotjuggler. In this screen shot "altitude" and "stbd_velocity" are clearly not matching up.

![image](https://github.com/PlotJuggler/plotjuggler-ros-plugins/assets/5939135/101b876d-80b5-46f4-96b4-8ea3059e8eac)

ubuntu 22.04 installed with sudo apt install ros-humble-plotjuggler ros-humble-plotjuggler-ros

**Comment by facontidavide** [comment] 2023-11-27 21:34
This seems to be a custom message, ins't it? 
Can you kindly share a rosbag recorded as MCAP?

**Comment by facontidavide** [comment] 2023-11-28 15:55
thanks

**Comment by facontidavide** [comment] 2023-12-13 09:02
Not having the message type **tetra_veh_interfaces** it is hard for me to debug.

Can you please check if opening directly the MCAP file using [PlotJuggler branch "ros_refactored"](https://github.com/facontidavide/PlotJuggler/tree/ros_refactored) fixes the issue?

**Comment by stewpend0us** [comment] 2023-12-13 14:42
Yes! that looks much better

**Comment by stewpend0us** [comment] 2023-12-13 14:45
Not while running it live though...

**Comment by facontidavide** [comment] 2023-12-13 17:08
please send me the code with **tetra_veh_interfaces** to reproduce, otherwise I can't run rosbag play

**Comment by stewpend0us** [comment] 2023-12-13 18:27
Here is a stripped down version. does this work?
[tetra_veh_interfaces.tar.gz](https://github.com/PlotJuggler/plotjuggler-ros-plugins/files/13664290/tetra_veh_interfaces.tar.gz)

**Comment by facontidavide** [comment] 2023-12-14 11:27
Just tried the **main** branch of this repo + **ros_refactored** branch of PlotJuggler and seems like everything works correctly.

I will temporarily close this issue, but please try this yourself and let me know if it works for you.

I will release soon **PlotJuggler** 3.9 and **plotjuggler_ros** 2.0, that will contain these changes.

![image](https://github.com/PlotJuggler/plotjuggler-ros-plugins/assets/2822888/6bd94c0e-b5a9-4b59-a344-a308b0a43489)

**Closed by facontidavide** 2023-12-14 11:27 UTC
Labels: bug

**Comment by stewpend0us** [comment] 2023-12-14 16:06
yes that combo does seem to be working. Thank you for the quick fix!!
